server:
  port: 9090
  servlet:
        # jsp修改之后立即生效
    context-path: /yx
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
  redis:
    pool: 6379
    host: localhost
  servlet:
    multipart:
      #上传单个文件大小的限制
      max-file-size: 100MB
      #
      max-request-size: 1000MB
mybatis-plus:
  type-aliases-package: com.baizhi.entity
  mapper-locations: com/zhaoj/mapper/*Mapper.xml

  configuration:
    #开启二级缓存
    cache-enabled: true
logging:
  level:
    com.zhaoj.dao: debug